spring:
  yanhongbin:
    ali:
      iot:
        config:
          # 阿里云物联平台账号信息
          accessKeyId: '*******'
          accessKeySecret: '********'
          # 物联网平台对应地区
          regionId: SHANGHAI
          # 阿里云账号UID
          uid: 1940213675463409
          # 物联平台产品key
          productKey: a1skKPGCozo
          # 消息处理器beanID配置，使用Mns模式时必须，key为产品key，value为消息处理器的对应BeanName
          message-processor-bean-id:
            a1skKPGCozo: defaultMessageProcessor
        # 连接相关配置
        connect:
          # 连接类型 支持 amqp，mns，http/2 （http/2 已被废弃）
          type: amqp
          # 服务端订阅开关，不配置默认不开启
          subscribe-switch: off
        # amqp连接信息配置，使用amqp模式时必须
        amqp:
          # 消费组id和对应的消息持利器BeanName配置
          consumer-group-message-config:
            - consumer-groupId: DEFAULT_GROUP
              message-processor-beanId: messageProcessor
          # 加密方法配置
          signMethod: hmacsha1
server:
  port: 12021
thread:
  pool:
    # 是否使用线程池处理消息，不使用则单线程阻塞处理
    thread-pool-switch: on
    # 以下相关配置均有默认值
    # 核心线程数
    core-pool-size: 4
    # 最大线程数
    maximum-pool-size: 4
    # 线程存活时间
    keep-alive-time: 0
    # 时间单位
    unit: milliseconds
    # 工作队列大小
    work-queue-size: 8

